name: Build and deploy preview on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJS ${{ matrix.node-version }} build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm run export

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GEEK_HOSTING }}'
          projectId: geek-hosting
          target: ruckgaber
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
